apiVersion: v1
kind: ReplicationController
metadata:
  name: flask-test-app-rc
spec:
  replicas: 2
  selector:
    app: flask-test-app
  template:
    metadata:
      labels:
        app: flask-test-app
    spec:
      containers:
      - name: flask-test-app
        image: bastianklein/flask-test-app
        ports:
        - containerPort: 80
          name: http
        env:
        - name: FLASK_APP
          value: 'testapp'
