apiVersion: v1
kind: ReplicationController
metadata:
  name: reverse-proxy
spec:
  replicas: 1
  selector:
    app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
      - name: reverse-proxy
        image: bastianklein/reverse-proxy-test-app
        ports:
        - containerPort: 80
          name: http
