apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reverse-proxy
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
      - name: reverse-proxy
        image: bastianklein/reverse-proxy-test-app
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
