apiVersion: v1
kind: Service
metadata:
  name: flask-test-app
spec:
  ports:
  - name: http
    nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: flask-test-app
  type: NodePort
