apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
spec:
  ports:
  - name: http
    nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: reverse-proxy
  type: NodePort
